# define stages
stages:
  - preparing
  - building
  - end

preparing:
  stage: preparing
  script:
    - apt-get update -qq && apt install git-lfs

building:
  stage: building
  script:
    - cd ./shell
    - bash ./ci_preparing.sh
    - bash ./manual_compress.sh

end:
  stage: end
  script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
      - git config user.email github-actions@github.com
      - if git diff-index --quiet HEAD --; then
      -   echo "No changes"
      - else
      -  git commit -m "[action-auto]:{commit images automatically.}"
      -  git push
      - fi
