# define stages
stages:
  - preparing
  - building
  - end

preparing:
  stage: preparing
  script:
  - apt install git-lfs

building:
  stage: building
  script:
  - cd ./shell
  - bash ./ci_preparing.sh
  - mv -f try_to_put_imgs_into_git.sh put_imgs_into_git.sh
  - bash ./manual_compress.sh

end:
  stage: end
  script:
    - exit 0


