name: CI
on: push

jobs:
  linux:
    name: Building test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        lfs: true

    - name: Prepare building
      run: |
        chmod +x ./res/*  
        chmod +x ./shell/*
        cd ./shell
        bash ./github_action_preparing.sh


    - name: Begin building
      run: |
        cd ./shell
        bash ./manual_compress.sh

    - name: Begin git-task
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "[action]:{action commit image file automatically.}"
        git push  # if you want to push it, please delete "#".

        ## TODO create a manual task to compress img. and create