name: CI
on: push

jobs:
  linux:
    name: Building test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with: 
        lfs: true

    - name: Prepare building
      run: |
        chmod +x ./res/*  
        chmod +x ./shell/*
        cd ./shell
        bash ./install_apps_in_githubaction.sh


    - name: Begin building
      run: |
        cd ./shell
        bash ./manual_compress.sh
          
