name: CI
on: push

jobs:
  linux:
    name: Building test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Begin building
      run: |
        chmod +x ./*.sh   
        chmod +x ./res/*
        bash ./manual_compress.sh
          
