name: Trigger-compression
on: [workflow_dispatch]

jobs:
  linux:
    name: Building test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        lfs: true

    - name: Prepare building
      run: |
        chmod +x ./res/*  
        chmod +x ./shell/*
        cd ./shell
        bash ./github_action_preparing.sh


    - name: Begin building
      run: |
        cd ./shell
        bash ./manual_compress.sh

    - name: Begin git-task
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git diff-index --quiet HEAD --; then
          echo "No changes"
        else
          git commit -m "[action-auto]:{commit images automatically.}"
          git push
        fi
        
        